// export const Type = {
//   ADD_TO_BASKET: "ADD_TO_BASKET",
//   REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
//   EMPTY_BASKET: "EMPTY_BASKET",
//   USER: "USER",
//   USER_INFO: "USER_INFO",
//   SET_ORDERS: "SET_ORDERS",
// };


export const Type = {
  ADD_TO_BASKET: "ADD_TO_BASKET",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
  CLEAR_BASKET: "CLEAR_BASKET",
  EMPTY_BASKET: "EMPTY_BASKET",
  SET_USER: "SET_USER",
};


// export const Type ={
//     ADD_TO_BASKET: 'ADD_TO_BASKET',
//     REMOVE_FROM_BASKET:'REMOVE_FROM_BASKET'

// }